ledger.id=0x03

# base config
nodes.gossipFqdnRestricted=false
staking.assumeContiguousPeriods=false
nodes.nodeRewardsEnabled=false

# ------------------------------ new configs for system-contract tests ------------------------------
# Contracts config
contracts.chainId=298
# ------- used for 'erc-events' tests
# 359 and 364 are decimal representations of `0x167` and `0x16c`
contracts.systemContract.hts.addresses=359,364
# ------- pectra support enabled
contracts.codeDelegations.enabled=true
# ---------------------------------------------

# ------------------------------ new configs for Ethereum execution spec tests ------------------------------
# gas limit
contracts.maxGasPerTransaction=120000000
contracts.maxGasPerSec=120000000
contracts.maxGasPerSecBackend=120000000
# transaction size limit
jumboTransactions.maxTxnSize=720000
jumboTransactions.ethereumMaxCallDataSize=720000
# redirects
consensus.handle.maxFollowingRecords=640