ledger.id=0x03

# base config
nodes.gossipFqdnRestricted=false
staking.assumeContiguousPeriods=false
nodes.nodeRewardsEnabled=false

# ------------------------------ new configs for system-contract tests ------------------------------
# Contracts config
contracts.chainId=298
# ------- used for 'erc-events' tests
# 359 and 364 are decimal representations of `0x167` and `0x16c`
contracts.systemContract.hts.addresses=359,364
# ------- pectra support enabled
contracts.codeDelegations.enabled=true
# ---------------------------------------------

# ------------------------------ New configs for Ethereum execution spec tests ------------------------------
# disable throttling
contracts.throttle.throttleByOpsDuration=false
throttle.throttleByGas=false
# gas limit
contracts.maxGasPerTransaction=150000000
contracts.maxGasPerSec=150000000
contracts.maxGasPerSecBackend=150000000
# transaction size limit
# All zero bytes: (gas_limit − 21,000) / 10 bytes = 14 997 900
# All non-zero bytes: (gas_limit − 21,000) / 40 bytes = 3 749 475
# AVG = (14 997 900 + 3 749 475) / 2 = 9 373 687,5
jumboTransactions.maxTxnSize=9000000
jumboTransactions.ethereumMaxCallDataSize=9000000
jumboTransactions.maxBytesPerSec=9000000
governanceTransactions.maxTxnSize=9000000
contracts.maxSerializedTraceDataBytes=9000000

# redirects
# Tests:
# - tests/prague/eip7702_set_code_tx/test_gas.py::test_gas_cost fixture: many_valid_authorizations_single_signer
# authorizations_count with 12M gas = ~439
consensus.handle.maxFollowingRecords=500