web3:
  resources:
    requests:
      memory: 300Mi
    limits:
      memory: 600Mi
  config:
    hiero:
      mirror:
        web3:
          evm:
            properties:
              # Needed for transfer events tests gas estimations for 0x16c contract
              contracts.systemContract.hts.addresses: "359,364"
rest:
  resources:
    requests:
      memory: 300Mi
    limits:
      memory: 400Mi
  env:
    # Needed for EIP-7702 (Pectra) response fields
    HIERO_MIRROR_REST_RESPONSE_ENABLEDELEGATIONADDRESS: "true"
importer:
  resources:
    requests:
      memory: 400Mi
    limits:
      memory: 500Mi