# This configuration[1] is used when `mocha` is invoked directly
# from the command line.
#
# [1] https://mochajs.org/running/configuring/

# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
spec:
  - test/**/*.test.ts

# https://mochajs.org/features/global-fixtures/
require:
  - test/scripts/build.ts
